[build]
    command = "echo 'default context'"
[[headers]]
for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
